---
spring:
  main:
    web-application-type: none

poll:
  server: https://api.ipify.org/
  cron: "0 */1 * * * *"

cloudflare:
  domain: YOUR_DOMAIN
  api:
    url: https://api.cloudflare.com/client/v4
    key: YOUR_CF_API_KEY
    email: YOUR_CF_EMAIL
