---
poll:
  server: https://api.ipify.org/
  cron: "0 */1 * * * *"

cloudflare:
  domain: YOUR_DOMAIN
  api:
    url: https://api.cloudflare.com/client/v4
    key: YOUR_CF_API_KEY
    email: YOUR_CF_EMAIL
  records: >
  #  some.record.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus