---
poll:
  server: https://api.ipify.org/
  cron: "0 */1 * * * *"

cloudflare:
  api-url: https://api.cloudflare.com/client/v4

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
