---
poll:
  server: https://api.ipify.org/
  cron: "0 */1 * * * *"

cloudflare:
  api-url: https://api.cloudflare.com/client/v4
  domains:
    ANY_WEBSITE_NAME:
      domain: yourpage.com
      api-email: YOUR_CF_EMAIL
      api-key: YOUR_CF_API_KEY
      zones:
        - ANY_ZONE_ID
        - ANY_ZONE_ID
      records:
        - ANY_RECORD_ID
        - ANY_RECORD_ID

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
