---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dns-updater
  name: dns-updater
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-updater
  template:
    metadata:
      labels:
        app: dns-updater
    spec:
      nodeSelector:
        worker: "true"
      containers:
        - env:
            - name: "poll.cron"
              value: "0 */1 * * * *"
            - name: "cloudflare.domain"
              value: "magnuen2k.com"
            - name: "cloudflare.api.email"
              value: "magnuen2k@gmail.com"
            - name: "cloudflare.api.key"
              valueFrom:
                secretKeyRef:
                  name: cf-secret
                  key: key
          image: registry.magnuen2k.com/homelab/util/dns-updater:latest
          name: dns-updater
          resources:
            limits:
              memory: "1Gi"
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-secret
