---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-updater
spec:
  template:
    spec:
      containers:
        - name: dns-updater
          env:
            - name: "poll.cron"
              value: "0 */1 * * * *"
            - name: "cloudflare.domains.magnuen2k.domain"
              value: "magnuen2k.com"
            - name: "cloudflare.domains.magnuen2k.api-email"
              value: "magnuen2k@gmail.com"
            - name: "cloudflare.domains.magnuen2k.api-key"
              valueFrom:
                secretKeyRef:
                  name: cf-secret
                  key: key
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1Gi"
