---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dns-updater
  namespace: homelab
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: homelab-cert
spec:
  host: dns.apps.lab.magnuen2k.com
  to:
    kind: Service
    name: dns-updater
    weight: 100
  port:
    targetPort: dns-updater
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
